---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.11 webserver wordpress.4labs.example chat.4labs.example
        - 172.16.0.12 graylog
        - 172.16.0.13 kibana kibana.4labs.example

    - name: Criando diretorio /opt/filebeat
      synchronize:
        src: files/filebeat
        dest: /opt

    - name: Criando diretorio /opt/logstash
      synchronize:
        src: files/logstash
        dest: /opt

    - name: Criando diretorio /opt/metricbeat
      synchronize:
        src: files/metricbeat
        dest: /opt

    - name: Criando diretorio /opt/nginx
      synchronize:
        src: files/nginx
        dest: /opt

    - name: Criando o arquivo syslog-tls.conf
      copy:
        src: files/client/syslog-tls.conf
        dest: /opt
        mode: 0644
